#!/bin/bash

#convert files in $1 into sentences per line file and put into $2 dir

for file in $1/*
do
  opennlp SentenceDetector lt-sent.bin < $file >> $2/`basename $file`
  sed -i '/^$/d' $2/`basename $file`
done
